package cli

var catOrder = []string{
	"Identity", "Configuration", "Security",
	"Development", "Editors", "Browsers",
	"Databases", "Containers", "Cloud",
	"Infrastructure", "Projects", "Virtualization",
	"Packages", "System", "Other",
}

var moduleGroups = map[string]string{
	"ssh":            "Identity",
	"gpg":            "Identity",
	"git":            "Configuration",
	"shell":          "Configuration",
	"dotfiles":       "Configuration",
	"vscode":         "Editors",
	"neovim":         "Editors",
	"firefox":        "Browsers",
	"chrome":         "Browsers",
	"chromium":       "Browsers",
	"brave":          "Browsers",
	"vivaldi":        "Browsers",
	"edge":           "Browsers",
	"opera":          "Browsers",
	"golang":         "Development",
	"nodejs":         "Development",
	"python":         "Development",
	"rust":           "Development",
	"java":           "Development",
	"docker":         "Containers",
	"postgres":       "Databases",
	"mysql":          "Databases",
	"mongodb":        "Databases",
	"redis":          "Databases",
	"sqlite":         "Databases",
	"cloud":          "Cloud",
	"kubernetes":     "Infrastructure",
	"repos":          "Projects",
	"certs":          "Security",
	"virtualization": "Virtualization",
	"apt":            "Packages",
	"snap":           "Packages",
	"flatpak":        "Packages",
	"system":         "System",
}
